name: Interactive SSH Kernel Build

# 触发条件：当你点击 GitHub 网页上的 "Run workflow" 时手动触发
on:
  workflow_dispatch:

jobs:
  ssh-build:
    runs-on: ubuntu-latest  # 这里就是标准的免费云端机器

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 【核心步骤】运行到这里会暂停，并弹出 SSH 连接信息
    - name: Setup tmate session (SSH 实时交互)
      uses: mxschmitt/action-tmate@v3
      if: always()
